name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Lint with flake8
      run: |
        flake8 src/ --max-line-length=88 --ignore=E203,W503

    - name: Check code formatting with black
      run: |
        black --check src/

    - name: Type checking with mypy
      run: |
        mypy src/ --ignore-missing-imports

    - name: Test with unittest
      run: |
        python -m unittest discover -s tests -p "test_*.py" -v

  build:
    needs: test
    runs-on: windows-latest
    if: github.event_name == 'release'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable
      run: |
        pyinstaller --clean autokeyboard.spec

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/AutoKeyboard-Presser.exe
        asset_name: AutoKeyboard-Presser.exe
        asset_content_type: application/octet-stream

  security:
    runs-on: windows-latest
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v4

    - name: Run security checks
      uses: securecodewarrior/github-action-security-scan@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
